version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ecg_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-ecg_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-SecOpsPassw0rd_2026!}
      POSTGRES_DB: ${POSTGRES_DB:-ethio_cyberguard}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/seeds/seeds.sql:/docker-entrypoint-initdb.d/02_seeds.sql
    networks:
      - ecg_network

  redis:
    image: redis:7-alpine
    container_name: ecg_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - ecg_network

  api:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.api
    container_name: ecg_api
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-ecg_admin}:${POSTGRES_PASSWORD:-SecOpsPassw0rd_2026!}@postgres:5432/${POSTGRES_DB:-ethio_cyberguard}
      REDIS_URL: redis://redis:6379/0
      API_SECRET_KEY: ${API_SECRET_KEY:-ecg_development_jwt_secret_key_change_in_prod}
    depends_on:
      - postgres
      - redis
    networks:
      - ecg_network

  web:
    build:
      context: ./apps/web
      dockerfile: ../../infrastructure/docker/Dockerfile.web
    container_name: ecg_web
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - ecg_network

networks:
  ecg_network:
    driver: bridge

volumes:
  postgres_data:
